name: Manter Supabase Ativo

on:
  schedule:
    - cron: '0 0 */3 * *' # Executa a cada 3 dias
  workflow_dispatch: # Permite rodar manualmente

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Forçar Consulta Real no Banco
        run: |
          curl -i -X GET "https://supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
