name: Manter Supabase Ativo

on:
  schedule:
    - cron: '0 0 */3 * *' # Executa automaticamente a cada 3 dias às 00:00 UTC
  workflow_dispatch: # Permite que você ative o teste manualmente quando quiser

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar requisicao externa
        run: |
          curl -i -X GET "https://supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
